version: "3"
services:
 web:
   build: dockerfiles/php-apache
   ports:
    - "80:80"

 db:
  build: dockerfiles/mysql
  ports:
   - "3306:3306"
  volumes:
   - /home/ubuntu/codeigniter-project/mydatabase/:/var/lib/mysql