version: "3"
services:
 web:
   build: dockerfiles/php-apache
   ports:
    - "80:80"

db:
    image: mysql:8.0
    container_name: ci4-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ci4_db
      MYSQL_USER: ci4user
      MYSQL_PASSWORD: ci4password
    ports:
      - "3306:3306"
    networks:
      - ci4-network

networks:
  ci4-network:
    driver: bridge