version: "3"
services:
 web:
   build: dockerfiles/php-apache
   ports:
    - "80:80"

 db:
  build: dockerfiles/mysql
  ports:
   - "3308:3308"
  volumes:
   - /c/xampp/htdocs/ci4crud/database/:/var/lib/mysql